#!/usr/bin/env python

"""Compile scripts into binary form."""

from glob import glob
import os

import chapter10
c10_path = os.path.dirname(os.path.dirname(chapter10.__file__))


def main():

    # Ensure PyInstaller is available.
    if os.system('which pyinstaller'):
        print 'PyInstaller not found. Try: pip install pyinstaller and run \
again.'
        return

    for script in glob('c10-*.py') + ['pcap2c10.py']:
        os.system('pyinstaller -p "%s" -F %s' % (c10_path, script))


if __name__ == "__main__":
    main()
